name: adhd_voice_assistant
description: "A voice-first assistant app designed for ADHD users with task management capabilities"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Speech Recognition
  speech_to_text: ^7.0.0
  
  # Text to Speech
  flutter_tts: ^4.0.2
  
  # HTTP Requests
  http: ^1.1.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Audio Processing
  record: ^5.0.4
  just_audio: ^0.9.36
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # Wake Word Detection (Alternative implementation)
  flutter_sound: ^9.2.13
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Date/Time handling
  intl: ^0.19.0
  
  # UUID generation
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700